version: '3'

services:
  web:
    build: .
    ports:
      - "8070:8020"
    volumes:
      - media_data:/opt/app/web_apps/media
    env_file:
      - .env
    restart: always

volumes:
  media_data: