version: '3'

services:
  web:
    build: .
    ports:
      - "8070:8020"
    volumes:
      # - ./staticfiles:/opt/app/web_apps/core/static
      - media_data:/opt/app/web_apps/media
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:
  media_data:
