# Generated by Django 5.0.9 on 2024-10-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter URL')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, help_text='Youtube URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
