# Generated by Django 5.0.9 on 2024-10-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_navigationsettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footertext',
            options={'verbose_name_plural': 'Footer Text'},
        ),
    ]
