# Generated by Django 4.2.16 on 2024-11-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_websitesettings_location_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='location_link',
            field=models.URLField(null=True, verbose_name='Location Url'),
        ),
    ]
