# Generated by Django 4.2.16 on 2024-11-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_navigationsettings_remove_footertext_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footertext',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='footertext',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='first_published_at',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='go_live_at',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='has_unpublished_changes',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='last_published_at',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='latest_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='live',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='live_revision',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='footertext',
            name='translation_key',
        ),
    ]
