# Generated by Django 5.0.9 on 2024-11-05 08:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_body_remove_homepage_hero_cta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_us_card',
            field=wagtail.fields.StreamField([('about_us', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 1: ('wagtail.blocks.TextBlock', (), {'max_length': 150}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_us_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
