# Generated by Django 4.2.16 on 2024-11-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0001_initial'),
        ('home', '0005_alter_carouselitem_link_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_section',
            field=models.ForeignKey(blank=True, help_text='First featured section for the homepage. Will display up to three child items.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blogpages.blogpage', verbose_name='Featured section 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blogpages.blogpagedetail', unique=True, verbose_name='Link Page'),
        ),
    ]
