# Generated by Django 4.2.16 on 2024-11-17 15:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogpages', '0001_initial'),
        ('home', '0006_homepage_featured_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cta_selection',
            field=wagtail.fields.StreamField([('cta_button', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('link', 1), ('external_link', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_section',
            field=models.ForeignKey(blank=True, help_text='First featured section for the homepage. Will display latest blog posts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blogpages.blogpage', verbose_name='Featured section'),
        ),
    ]
