# Generated by Django 4.2.16 on 2024-11-17 16:10

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_cta_selection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_us_card',
            field=wagtail.fields.StreamField([('about_us', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Icon to display before the title', 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'max_length': 150}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('icon', 1), ('text', 2)]], {})}, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_selection',
            field=wagtail.fields.StreamField([('cta_button', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 50}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Icon to display before the title', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('icon', 1), ('link', 2), ('external_link', 3)]], {})}, null=True),
        ),
    ]
