# Generated by Django 4.2.16 on 2024-11-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('home', '0008_alter_homepage_about_us_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Select the image collection for this carousel.', limit_choices_to=models.Q(('name__in', ['Root']), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collection_introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page'),
        ),
    ]
