# Generated by Django 4.2.16 on 2024-11-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_gallery'),
        ('home', '0009_homepage_collection_homepage_collection_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='collection_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.gallery'),
        ),
    ]
